### ISSUE TITLE
Not an issue but question | Redesign menu.py code explain

### ISSUE THREAD

**Issue by andynvo** [nickdvlpr/Redesign#15]
@nickdvlpr 

Can you help me understand your code better so that I may use for my own add-on?  What I want to do is change the menu bar from [File, Edit, Tools, Help] to [File, Edit, Tools, Add-ons, Help].  I want to move all the add-on related actions to the new menu "Add-ons" instead of my having my Tools menu ever expanding.  I'm still new to Python and don't quite understand all the Anki related commands.

**Comment by nickdvlpr** [comment]
@andynvo Hi! Unfortunately, this add-on is no longer updated because of the changes made to Anki's main code base in recent versions. I haven't kept up with the changes in Anki so I likely would not be of much assistance. I'd recommend looking at other updated add-ons, perhaps downloading them to see if they have menus similar to what you are looking for in your add-on.
